apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: e2e-js-test-pipelinerun 
spec:
  pipelineRef:
    name: e2e-js-test-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: e2e-js-test-resource
  params:
    - name: IMAGE
      value: "danya97/e2e-test-js"
    - name: CONTEXT
      value: "/workspace/level3-project/e2e-test-js"
    - name: DOCKERFILE
      value: "/workspace/level3-project/e2e-test-js/Dockerfile"
  serviceAccountName: danya-docker-hub
