apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: shipping-pipelinerun 
spec:
  pipelineRef:
    name: shipping-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: shipping-resource
  params:
    - name: CONTEXT
      value: "/workspace/level3-project/shipping"
    - name: DOCKERFILE
      value: "/workspace/level3-project/shipping/Dockerfile"
    - name: pathToYamlFile
      value: "level3-project/deploy/shipping-dep.yaml"
    - name: imageUrl
      value: "danya97/shipping"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "danya97/shipping"
      
  serviceAccountName: danya-docker-hub
