apiVersion: v1
kind: Secret
metadata:
  name: danyacreds
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/  # Described below
type: kubernetes.io/basic-auth
stringData:
  username: danya97
  password: 

