apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-js-test-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  params:
    - name: IMAGE
      type: string
      default: "danya97/e2e-test-js"
    - name: DOCKERFILE
      type: string
      default: "/workspace/level3-project/e2e-test-js/Dockerfile"
    - name: CONTEXT
      type: string
      default: "/workspace/level3-project/e2e-test-js"
  tasks:
  - name: build-push-image
    taskRef:
      name: build-push-task
    params:
      - name: IMAGE
        value: "$(params.IMAGE)"
      - name: DOCKERFILE
        value: "$(params.DOCKERFILE)"
      - name: CONTEXT
        value: "$(params.CONTEXT)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
