apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: front-end-resource
  namespace: test
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/Danya-Mudaifea/Level3-Project
