apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-e2e-test-task
spec:
  resources:
    inputs:
      - name: level3-project
        type: git
  steps:
  - name: run-test
    image: danya97/e2e-test-js
    command: ["/bin/bash"]
    args: ['-c', "/e2e-test-js/runner.sh"] 
