---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    name: kibana
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kibana
  replicas: 1
  template:
    metadata:
      labels:
        name: kibana
    spec:
      containers:
       - image: kibana:7.9.2
         name: kibana
         ports:
          - name: kibana
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    name: kibana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 31601 
  selector:
    name: kibana
